spring:
  application:
    name: solution
  profiles:
    active: "${SYSTEM_PROFILE}"
    include:
      - logging
  output:
    ansi:
      enabled: ALWAYS
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  datasource:
    url: jdbc:mysql://localhost:3306/solution_db
    username: root
    password: admin
server:
  port: 8090
  servlet:
    context-path: /demo-api
mybatis:
  config-location: classpath:mybatis-config.xml
springdoc:
  swagger-ui:
    path: /earomero-documentation
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /earomero-api-docs
